name: CI

on: [push]

jobs:
  checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install deps
        run: npm ci

      - name: Run linters
        run: npm run checkup

      - name: Run tests
        run: npm run test
